In [30]:
import pandas as pd
import numpy  as np

data = pd.ExcelFile("data_CRIR_anon.xlsx")

data_P = pd.read_excel(data, 'P')
data_S = pd.read_excel(data, 'S')
data_EF = pd.read_excel(data, 'EF')
data_T = pd.read_excel(data, 'T')

In [31]:
data_EF.head()

,essai,P6_reel,E1,V,E2,P1_reel,Lq1_reel,Lq2_reel,Lq_reel,Lq_target,E1.1,E1.2,E1.3,E2.1,E2.2,E2.3,E2.4
0,NaN,NaN,"moyenne E1.1, E1.2, E1.3",NaN,lié à P3,NaN,NaN,NaN,moyenne Lq1 et Lq2,identique à une autre col,NaN,NaN,NaN,meme param que les autres E2,meme param que les autres E2,meme param que les autres E2,meme param que les autres E2
1,392291.0,1.0,87.066667,0.0,NaN,15.12,NaN,NaN,NaN,3.7,87.4,86.8,87.0,NaN,NaN,NaN,NaN
2,392291.0,1.0,87.3,0.0,NaN,15.12,NaN,NaN,NaN,3.7,86.6,87.6,87.7,NaN,NaN,NaN,NaN
3,392291.0,1.0,87.433333,0.0,NaN,15.12,NaN,NaN,NaN,3.7,88.0,87.2,87.1,NaN,NaN,NaN,NaN
4,392291.0,1.0,86.266667,0.0,NaN,15.12,NaN,NaN,NaN,3.7,85.6,86.4,86.8,NaN,NaN,NaN,NaN

In [32]:
data_EF_clean = data_EF.drop(data_EF[data_EF['P6_reel']==1.00].index)
data_EF_clean.drop(0, inplace=True)
data_EF_clean.head(10)

,essai,P6_reel,E1,V,E2,P1_reel,Lq1_reel,Lq2_reel,Lq_reel,Lq_target,E1.1,E1.2,E1.3,E2.1,E2.2,E2.3,E2.4
329,392291.0,3.20,86.5,0.0,1103,15.12,4.3,4.2,4.3,3.7,86.4,86.9,86.1,NaN,NaN,NaN,NaN
330,392291.0,3.20,84.5,0.0,876,15.12,3.8,3.9,3.8,3.7,85.1,84.2,84.3,NaN,NaN,NaN,NaN
331,392291.0,3.20,87.9,0.0,982,15.12,3.9,3.8,3.9,3.7,88.8,87.8,87.1,NaN,NaN,NaN,NaN
332,392291.0,3.20,84.6,0.0,905,15.12,4.1,3.9,4,3.7,85.1,83.7,84.9,NaN,NaN,NaN,NaN
333,392291.0,3.20,88.4,0.0,1087,15.12,4.3,4.2,4.3,3.7,90.9,87.2,87.2,45,34,48,39
334,392291.0,3.20,84.9,0.0,874,15.12,3.8,3.9,3.8,3.7,85.4,85.1,84.3,58,54,49,50
335,392291.0,3.20,85.5,0.0,883,15.12,3.9,3.8,3.9,3.7,87.0,84.2,85.4,56,51,51,49
336,392291.0,3.20,84.6,0.0,900,15.12,4.1,3.9,4,3.7,84.1,84.4,85.3,49,47,42,38
337,392291.0,4.92,86.3,0.0,1079,15.12,4.5,4.1,4.3,3.7,85.7,86.5,86.8,NaN,NaN,NaN,NaN
338,392291.0,4.92,84.1,0.0,874,15.12,4.1,3.7,3.9,3.7,84.4,83.5,84.6,NaN,NaN,NaN,NaN

In [33]:
data_P.drop(0, inplace=True)

In [34]:
data_EF_clean['round_P6']= data_EF_clean['P6_reel'].round(0)

In [35]:
df= pd.merge(data_EF_clean, data_P, how='left', left_on=['essai','round_P6'] , right_on=['essai','P6_target'])
df.to_csv('mes_donnees.csv', sep=';', index=False, encoding='utf-8-sig')
df.head(25)

,essai,P6_reel,E1,V,E2,P1_reel,Lq1_reel,Lq2_reel,Lq_reel,Lq_target_x,...,F5,P1_target,C,P2,Lt,Lq_target_y,P3,P4,P5,P6_target
0,392291.0,3.20,86.5,0.0,1103,15.12,4.3,4.2,4.3,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,48,3.0
1,392291.0,3.20,84.5,0.0,876,15.12,3.8,3.9,3.8,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,48,3.0
2,392291.0,3.20,87.9,0.0,982,15.12,3.9,3.8,3.9,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,48,3.0
3,392291.0,3.20,84.6,0.0,905,15.12,4.1,3.9,4,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,48,3.0
4,392291.0,3.20,88.4,0.0,1087,15.12,4.3,4.2,4.3,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,48,3.0
5,392291.0,3.20,84.9,0.0,874,15.12,3.8,3.9,3.8,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,48,3.0
6,392291.0,3.20,85.5,0.0,883,15.12,3.9,3.8,3.9,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,48,3.0
7,392291.0,3.20,84.6,0.0,900,15.12,4.1,3.9,4,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,48,3.0
8,392291.0,4.92,86.3,0.0,1079,15.12,4.5,4.1,4.3,3.7,...,595.0,15.0,2,87.0,R,0.04,16.0,14.712644,80,5.0
9,392291.0,4.92,84.1,0.0,874,15.12,4.1,3.7,3.9,3.7,...,595.0,15.0,2,87.0,R,0.04,16.0,14.712644,80,5.0
10,392291.0,4.92,86,0.0,919,15.12,3.8,4.1,3.9,3.7,...,595.0,15.0,2,87.0,R,0.04,16.0,14.712644,80,5.0
11,392291.0,4.92,82.9,0.0,846,15.12,4.1,4.3,4.2,3.7,...,595.0,15.0,2,87.0,R,0.04,16.0,14.712644,80,5.0
12,392291.0,4.92,86.8,0.0,1107,15.12,4.5,4.1,4.3,3.7,...,595.0,15.0,2,87.0,R,0.04,16.0,14.712644,80,5.0
13,392291.0,4.92,83.9,0.0,870,15.12,4.1,3.7,3.9,3.7,...,595.0,15.0,2,87.0,R,0.04,16.0,14.712644,80,5.0
14,392291.0,4.92,85.3,0.0,913,15.12,3.8,4.1,3.9,3.7,...,595.0,15.0,2,87.0,R,0.04,16.0,14.712644,80,5.0
15,392291.0,4.92,83.2,0.0,854,15.12,4.1,4.3,4.2,3.7,...,595.0,15.0,2,87.0,R,0.04,16.0,14.712644,80,5.0
16,392291.0,7.04,85,0.0,1087,15.12,4.4,4.0,4.2,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,112,7.0
17,392291.0,7.04,82.5,0.0,877,15.12,4.2,3.8,4,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,112,7.0
18,392291.0,7.04,83.5,0.0,893,15.12,3.9,3.9,3.9,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,112,7.0
19,392291.0,7.04,82.8,0.0,852,15.12,4.3,4.3,4.3,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,112,7.0
20,392291.0,7.04,84.9,0.0,1084,15.12,4.4,4.0,4.2,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,112,7.0
21,392291.0,7.04,83.8,0.0,889,15.12,4.2,3.8,4,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,112,7.0
22,392291.0,7.04,84.4,0.0,894,15.12,3.9,3.9,3.9,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,112,7.0
23,392291.0,7.04,82.5,0.0,864,15.12,4.3,4.3,4.3,3.7,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,112,7.0
24,392292.0,3.20,87.9,0.0,1010,15.73,4.9,4.7,4.8,3.3,...,595.0,15.0,0.05,87.0,R,0.04,16.0,14.712644,48,3.0

In [36]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_normalize = df.copy()

df_normalize['F1'] = df_normalize['F1'].map({'Cold': 0, 'FME': 1})
df_normalize['Lt'] = df_normalize['Lt'].map({'F': 0, 'G': 1})

colonnes_a_enlever = ['date', 'condition', 'essai', 'P6_reel']
masque = ~df_normalize.columns.isin(colonnes_a_enlever)

df_normalize.loc[:, masque] = scaler.fit_transform(df_normalize.loc[:, masque])

df_normalize.head()

,essai,P6_reel,E1,V,E2,P1_reel,Lq1_reel,Lq2_reel,Lq_reel,Lq_target_x,...,F5,P1_target,C,P2,Lt,Lq_target_y,P3,P4,P5,P6_target
0,392291.0,3.2,0.508681,0.0,0.762007,0.531993,0.140432,0.086909,0.139073,0.105263,...,1.0,0.545455,0.0,0.0,NaN,0.0,0.5,0.646018,0.0,0.0
1,392291.0,3.2,0.480526,0.0,0.599283,0.531993,0.063272,0.053905,0.056291,0.105263,...,1.0,0.545455,0.0,0.0,NaN,0.0,0.5,0.646018,0.0,0.0
2,392291.0,3.2,0.52839,0.0,0.675269,0.531993,0.078704,0.042904,0.072848,0.105263,...,1.0,0.545455,0.0,0.0,NaN,0.0,0.5,0.646018,0.0,0.0
3,392291.0,3.2,0.481933,0.0,0.620072,0.531993,0.109568,0.053905,0.089404,0.105263,...,1.0,0.545455,0.0,0.0,NaN,0.0,0.5,0.646018,0.0,0.0
4,392291.0,3.2,0.535429,0.0,0.750538,0.531993,0.140432,0.086909,0.139073,0.105263,...,1.0,0.545455,0.0,0.0,NaN,0.0,0.5,0.646018,0.0,0.0

In [37]:
df_normalize.to_csv('mes_donnees_normalisées.csv', sep=';', index=False, encoding='utf-8-sig')

In [39]:
#Régression linéaire en supprimant les lignes NA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

colonnes_utiles = ["P1_reel", "P2", "Lt", "Lq_reel", "P4", "P5", "V", "E2", "P6_reel", "E1"]
masque = df_normalize.columns.isin(colonnes_utiles)
df2 = df_normalize.loc[:, masque]

df_normalizedrop = df2.dropna()
df_normalizedrop.head()
print(len(df_normalizedrop))

X = df_normalizedrop.drop(columns = ["E1"])
Y = df_normalizedrop["E1"]

print(X,Y)

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)

modele = LinearRegression()
modele.fit(X_train, y_train)

test = modele.predict(X_test)

erreur = mean_absolute_error(y_test, test)

print(f"Le modèle se trompe en moyenne de : {erreur}")

430
     P6_reel    V        E2   P1_reel   Lq_reel   P2   Lt   P4      P5
176     5.12  0.0  0.498208  0.016453  0.437086  1.0  0.0  0.0  0.1875
177     5.12  0.0  0.448029  0.016453  0.321192  1.0  0.0  0.0  0.1875
178     5.12  0.0  0.463082  0.016453  0.238411  1.0  0.0  0.0  0.1875
179     5.12  0.0  0.495341  0.016453  0.221854  1.0  0.0  0.0  0.1875
180     5.12  0.0  0.507527  0.016453  0.437086  1.0  0.0  0.0  0.1875
..       ...  ...       ...       ...       ...  ...  ...  ...     ...
699     5.12  0.0  0.682437  0.957952  0.701987  0.0  0.0  1.0  0.8125
700     5.12  0.0  0.863082  0.957952  0.668874  0.0  0.0  1.0  0.8125
701     5.12  0.0  0.832258  0.957952  0.602649  0.0  0.0  1.0  0.8125
702     5.12  0.0  0.894624  0.957952  0.586093  0.0  0.0  1.0  0.8125
703     5.12  0.0  0.687455  0.957952  0.701987  0.0  0.0  1.0  0.8125

[430 rows x 9 columns] 176    0.938057
177    0.864852
178    0.877522
179    0.864852
180    0.923979
         ...
699    0.428437
700    0.483341
701    0.481933
702    0.480526
703    0.434069
Name: E1, Length: 430, dtype: float64
Le modèle se trompe en moyenne de : 0.0741802487676467

In [ ]:
#Régression linéaire N°2 en supprimant les lignes NA (Calcul des colonnes puis moyenne)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

colonnes_utiles = ["P1_reel", "P2", "Lt", "Lq_reel", "P4", "P5", "V", "E2", "P6_reel", "E1", 'E2.1']
masque = df_normalize.columns.isin(colonnes_utiles)
df2 = df_normalize.loc[:, masque]

df_normalizedrop = df2.dropna()
df_normalizedrop.head()
print(len(df_normalizedrop))

X1 = df_normalizedrop.drop(columns = ['E2.1'])
Y1 = df_normalizedrop['E2.1']

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, Y1, test_size = 0.2)

modele = LinearRegression()
modele.fit(X1_train, y1_train)

test1 = modele.predict(X1_test)

colonnes_utiles = ["P1_reel", "P2", "Lt", "Lq_reel", "P4", "P5", "V", "E2", "P6_reel", "E1", 'E2.2']
masque = df_normalize.columns.isin(colonnes_utiles)
df2 = df_normalize.loc[:, masque]

df_normalizedrop = df2.dropna()
df_normalizedrop.head()
print(len(df_normalizedrop))

X2 = df_normalizedrop.drop(columns = ['E2.2'])
Y2 = df_normalizedrop['E2.2']

X2_train, X2_test, y2_train, y2_test = train_test_split(X2, Y2, test_size = 0.2)

modele = LinearRegression()
modele.fit(X2_train, y2_train)

test2 = modele.predict(X2_test)

colonnes_utiles = ["P1_reel", "P2", "Lt", "Lq_reel", "P4", "P5", "V", "E2", "P6_reel", "E1", 'E2.3']
masque = df_normalize.columns.isin(colonnes_utiles)
df2 = df_normalize.loc[:, masque]

df_normalizedrop = df2.dropna()
df_normalizedrop.head()
print(len(df_normalizedrop))

X3 = df_normalizedrop.drop(columns = ['E2.3'])
Y3 = df_normalizedrop['E2.3']

X3_train, X3_test, y3_train, y3_test = train_test_split(X3, Y3, test_size = 0.2)

modele = LinearRegression()
modele.fit(X3_train, y3_train)

test3 = modele.predict(X_test)

colonnes_utiles = ["P1_reel", "P2", "Lt", "Lq_reel", "P4", "P5", "V", "E2", "P6_reel", "E1", 'E2.4']
masque = df_normalize.columns.isin(colonnes_utiles)
df2 = df_normalize.loc[:, masque]

df_normalizedrop = df2.dropna()
df_normalizedrop.head()
print(len(df_normalizedrop))

X4 = df_normalizedrop.drop(columns = ['E2.4'])
Y4 = df_normalizedrop['E2.4']

X4_train, X4_test, y4_train, y4_test = train_test_split(X4, Y4, test_size = 0.2)

modele = LinearRegression()
modele.fit(X4_train, y4_train)

test4 = modele.predict(X4_test)

df = df.apply(pd.to_numeric, errors='coerce')
t1 = test1.astype(float)
t2 = test2.astype(float)
t3 = test3.astype(float)
t4 = test4.astype(float)
y1t = y1_test.astype(float)
y2t = y2_test.astype(float)
y3t = y3_test.astype(float)
y4t = y4_test.astype(float)

Moyenne_reelle = (y1t.values + y2t.values + y3t.values + y4t.values)/4
Moyenne = (t1 + t2 + t3 + t4) / 4

erreur = mean_absolute_error(Moyenne, Moyenne_reelle)

print(f"Le modèle se trompe en moyenne de : {erreur}")

215
215
215
215
43 43
Le modèle se trompe en moyenne de : 0.028416163369211222

In [ ]:

#Régression linéaire N°2 en supprimant les lignes NA (calcul direct moyenne)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

df_normalize = df_normalize.apply(pd.to_numeric, errors='coerce')

colonnes_a_moyenner = ['E2.1', 'E2.2', 'E2.3', 'E2.4']
df_normalize['E2_Moyenne'] = df_normalize[colonnes_a_moyenner].mean(axis=1)

colonnes_utiles = ["P1_reel", "P2", "Lt", "Lq_reel", "P4", "P5", "V", "E2", "P6_reel", "E1", "E2_Moyenne"]
df_reduit = df_normalize[colonnes_utiles]

df_propre = df_reduit.dropna()
print(f"Nombre de lignes conservées pour l'entraînement : {len(df_propre)}")

X = df_propre.drop(columns=['E2_Moyenne'])
Y = df_propre['E2_Moyenne']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

modele = LinearRegression()
modele.fit(X_train, y_train)

predictions = modele.predict(X_test)
erreur = mean_absolute_error(y_test, predictions)

print(f"Le modèle se trompe en moyenne de : {erreur}")

Nombre de lignes conservées pour l'entraînement : 215
Le modèle se trompe en moyenne de : 0.04680520906322092