In [27]:
import pandas as pd

data = pd.ExcelFile("data_CRIR_anon.xlsx")

data_P = pd.read_excel(data, 'P')
data_S = pd.read_excel(data, 'S')
data_EF = pd.read_excel(data, 'EF')
data_T = pd.read_excel(data, 'T')

In [28]:
data_EF.head()

,essai,P6_reel,E1,V,E2,P1_reel,Lq1_reel,Lq2_reel,Lq_reel,Lq_target,E1.1,E1.2,E1.3,E2.1,E2.2,E2.3,E2.4
0,NaN,NaN,"moyenne E1.1, E1.2, E1.3",NaN,lié à P3,NaN,NaN,NaN,moyenne Lq1 et Lq2,identique à une autre col,NaN,NaN,NaN,meme param que les autres E2,meme param que les autres E2,meme param que les autres E2,meme param que les autres E2
1,392291.0,1.0,87.066667,0.0,NaN,15.12,NaN,NaN,NaN,3.7,87.4,86.8,87.0,NaN,NaN,NaN,NaN
2,392291.0,1.0,87.3,0.0,NaN,15.12,NaN,NaN,NaN,3.7,86.6,87.6,87.7,NaN,NaN,NaN,NaN
3,392291.0,1.0,87.433333,0.0,NaN,15.12,NaN,NaN,NaN,3.7,88.0,87.2,87.1,NaN,NaN,NaN,NaN
4,392291.0,1.0,86.266667,0.0,NaN,15.12,NaN,NaN,NaN,3.7,85.6,86.4,86.8,NaN,NaN,NaN,NaN

In [29]:
data_EF_clean = data_EF.drop(data_EF[data_EF['P6_reel']==1.00].index)
data_EF_clean.drop(0, inplace=True)
data_EF_clean.head(10)

,essai,P6_reel,E1,V,E2,P1_reel,Lq1_reel,Lq2_reel,Lq_reel,Lq_target,E1.1,E1.2,E1.3,E2.1,E2.2,E2.3,E2.4
329,392291.0,3.20,86.5,0.0,1103,15.12,4.3,4.2,4.3,3.7,86.4,86.9,86.1,NaN,NaN,NaN,NaN
330,392291.0,3.20,84.5,0.0,876,15.12,3.8,3.9,3.8,3.7,85.1,84.2,84.3,NaN,NaN,NaN,NaN
331,392291.0,3.20,87.9,0.0,982,15.12,3.9,3.8,3.9,3.7,88.8,87.8,87.1,NaN,NaN,NaN,NaN
332,392291.0,3.20,84.6,0.0,905,15.12,4.1,3.9,4,3.7,85.1,83.7,84.9,NaN,NaN,NaN,NaN
333,392291.0,3.20,88.4,0.0,1087,15.12,4.3,4.2,4.3,3.7,90.9,87.2,87.2,45,34,48,39
334,392291.0,3.20,84.9,0.0,874,15.12,3.8,3.9,3.8,3.7,85.4,85.1,84.3,58,54,49,50
335,392291.0,3.20,85.5,0.0,883,15.12,3.9,3.8,3.9,3.7,87.0,84.2,85.4,56,51,51,49
336,392291.0,3.20,84.6,0.0,900,15.12,4.1,3.9,4,3.7,84.1,84.4,85.3,49,47,42,38
337,392291.0,4.92,86.3,0.0,1079,15.12,4.5,4.1,4.3,3.7,85.7,86.5,86.8,NaN,NaN,NaN,NaN
338,392291.0,4.92,84.1,0.0,874,15.12,4.1,3.7,3.9,3.7,84.4,83.5,84.6,NaN,NaN,NaN,NaN