In [1]:
import pandas as pd
import numpy as np

data = pd.ExcelFile("data_CRIR_anon.xlsx")

data_P = pd.read_excel(data, 'P') #Ouverture des différentes tables
data_S = pd.read_excel(data, 'S')
data_EF = pd.read_excel(data, 'EF')
data_T = pd.read_excel(data, 'T')

##on enlève la première ligne qui correspond à des commentaires
data_P.drop(0, inplace=True)
data_S.drop(0, inplace=True)

In [2]:
data_EF_clean = data_EF.drop(data_EF[data_EF['P6_reel']==1.00].index)
data_EF_clean.drop(0, inplace=True)
data_EF_clean.head(10)

,essai,P6_reel,E1,V,E2,P1_reel,Lq1_reel,Lq2_reel,Lq_reel,Lq_target,E1.1,E1.2,E1.3,E2.1,E2.2,E2.3,E2.4
329,392291.0,3.20,86.5,0.0,1103,15.12,4.3,4.2,4.3,3.7,86.4,86.9,86.1,NaN,NaN,NaN,NaN
330,392291.0,3.20,84.5,0.0,876,15.12,3.8,3.9,3.8,3.7,85.1,84.2,84.3,NaN,NaN,NaN,NaN
331,392291.0,3.20,87.9,0.0,982,15.12,3.9,3.8,3.9,3.7,88.8,87.8,87.1,NaN,NaN,NaN,NaN
332,392291.0,3.20,84.6,0.0,905,15.12,4.1,3.9,4,3.7,85.1,83.7,84.9,NaN,NaN,NaN,NaN
333,392291.0,3.20,88.4,0.0,1087,15.12,4.3,4.2,4.3,3.7,90.9,87.2,87.2,45,34,48,39
334,392291.0,3.20,84.9,0.0,874,15.12,3.8,3.9,3.8,3.7,85.4,85.1,84.3,58,54,49,50
335,392291.0,3.20,85.5,0.0,883,15.12,3.9,3.8,3.9,3.7,87.0,84.2,85.4,56,51,51,49
336,392291.0,3.20,84.6,0.0,900,15.12,4.1,3.9,4,3.7,84.1,84.4,85.3,49,47,42,38
337,392291.0,4.92,86.3,0.0,1079,15.12,4.5,4.1,4.3,3.7,85.7,86.5,86.8,NaN,NaN,NaN,NaN
338,392291.0,4.92,84.1,0.0,874,15.12,4.1,3.7,3.9,3.7,84.4,83.5,84.6,NaN,NaN,NaN,NaN

In [3]:
data_EF_clean['round_P6']= data_EF_clean['P6_reel'].round(0)

In [4]:
df= pd.merge(data_EF_clean, data_P, how='left', left_on=['essai','round_P6'] , right_on=['essai','P6_target'])

In [5]:
data_S['S1'] = pd.to_numeric(data_S['S1'], errors='coerce')
data_S_m = data_S.groupby('essai', as_index=False).agg(
    S_moy=('S1', 'mean'),
    sigma_S=('S1', 'std')
)
data_S_m['essai'] = data_S_m['essai'].astype(int)
data_S_m.head()

    essai     S_moy   sigma_S
0  390310  2.763667  0.414240
1  392291  2.992202  0.551089
2  392292  3.296931  0.549037
3  392293  2.595811  0.471396
4  392294  3.354443  0.585051

In [6]:
df= pd.merge(df, data_S_m, how='left', left_on=['essai'] , right_on=['essai'])
df.to_csv('mes_donnees.csv', sep=';', index=False, encoding='utf-8-sig')
df.head(25)

,essai,P6_reel,E1,V,E2,P1_reel,Lq1_reel,Lq2_reel,Lq_reel,Lq_target_x,...,C,P2,Lt,Lq_target_y,P3,P4,P5,P6_target,S_moy,sigma_S
0,392291.0,3.20,86.5,0.0,1103,15.12,4.3,4.2,4.3,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,48,3.0,2.992202,0.551089
1,392291.0,3.20,84.5,0.0,876,15.12,3.8,3.9,3.8,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,48,3.0,2.992202,0.551089
2,392291.0,3.20,87.9,0.0,982,15.12,3.9,3.8,3.9,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,48,3.0,2.992202,0.551089
3,392291.0,3.20,84.6,0.0,905,15.12,4.1,3.9,4,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,48,3.0,2.992202,0.551089
4,392291.0,3.20,88.4,0.0,1087,15.12,4.3,4.2,4.3,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,48,3.0,2.992202,0.551089
5,392291.0,3.20,84.9,0.0,874,15.12,3.8,3.9,3.8,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,48,3.0,2.992202,0.551089
6,392291.0,3.20,85.5,0.0,883,15.12,3.9,3.8,3.9,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,48,3.0,2.992202,0.551089
7,392291.0,3.20,84.6,0.0,900,15.12,4.1,3.9,4,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,48,3.0,2.992202,0.551089
8,392291.0,4.92,86.3,0.0,1079,15.12,4.5,4.1,4.3,3.7,...,2,87.0,R,0.04,16.0,14.712644,80,5.0,2.992202,0.551089
9,392291.0,4.92,84.1,0.0,874,15.12,4.1,3.7,3.9,3.7,...,2,87.0,R,0.04,16.0,14.712644,80,5.0,2.992202,0.551089
10,392291.0,4.92,86,0.0,919,15.12,3.8,4.1,3.9,3.7,...,2,87.0,R,0.04,16.0,14.712644,80,5.0,2.992202,0.551089
11,392291.0,4.92,82.9,0.0,846,15.12,4.1,4.3,4.2,3.7,...,2,87.0,R,0.04,16.0,14.712644,80,5.0,2.992202,0.551089
12,392291.0,4.92,86.8,0.0,1107,15.12,4.5,4.1,4.3,3.7,...,2,87.0,R,0.04,16.0,14.712644,80,5.0,2.992202,0.551089
13,392291.0,4.92,83.9,0.0,870,15.12,4.1,3.7,3.9,3.7,...,2,87.0,R,0.04,16.0,14.712644,80,5.0,2.992202,0.551089
14,392291.0,4.92,85.3,0.0,913,15.12,3.8,4.1,3.9,3.7,...,2,87.0,R,0.04,16.0,14.712644,80,5.0,2.992202,0.551089
15,392291.0,4.92,83.2,0.0,854,15.12,4.1,4.3,4.2,3.7,...,2,87.0,R,0.04,16.0,14.712644,80,5.0,2.992202,0.551089
16,392291.0,7.04,85,0.0,1087,15.12,4.4,4.0,4.2,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,112,7.0,2.992202,0.551089
17,392291.0,7.04,82.5,0.0,877,15.12,4.2,3.8,4,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,112,7.0,2.992202,0.551089
18,392291.0,7.04,83.5,0.0,893,15.12,3.9,3.9,3.9,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,112,7.0,2.992202,0.551089
19,392291.0,7.04,82.8,0.0,852,15.12,4.3,4.3,4.3,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,112,7.0,2.992202,0.551089
20,392291.0,7.04,84.9,0.0,1084,15.12,4.4,4.0,4.2,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,112,7.0,2.992202,0.551089
21,392291.0,7.04,83.8,0.0,889,15.12,4.2,3.8,4,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,112,7.0,2.992202,0.551089
22,392291.0,7.04,84.4,0.0,894,15.12,3.9,3.9,3.9,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,112,7.0,2.992202,0.551089
23,392291.0,7.04,82.5,0.0,864,15.12,4.3,4.3,4.3,3.7,...,0.05,87.0,R,0.04,16.0,14.712644,112,7.0,2.992202,0.551089
24,392292.0,3.20,87.9,0.0,1010,15.73,4.9,4.7,4.8,3.3,...,0.05,87.0,R,0.04,16.0,14.712644,48,3.0,3.296931,0.549037

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_normalize = df.copy() #copie du tableau

df_normalize['F1'] = df_normalize['F1'].map({'Cold': 0, 'FME': 1})
df_normalize['Lt'] = df_normalize['Lt'].map({'F': 0, 'G': 1})

colonnes_a_enlever = ['date', 'condition', 'essai', 'P6_reel'] #On enlève les colonnes qui ne sont pas des nombres et qui ne sont pas utiles
masque = ~df_normalize.columns.isin(colonnes_a_enlever)

df_normalize.loc[:, masque] = scaler.fit_transform(df_normalize.loc[:, masque]) #On normalise

df_normalize.head()

,essai,P6_reel,E1,V,E2,P1_reel,Lq1_reel,Lq2_reel,Lq_reel,Lq_target_x,...,C,P2,Lt,Lq_target_y,P3,P4,P5,P6_target,S_moy,sigma_S
0,392291.0,3.2,0.508681,0.0,0.762007,0.531993,0.140432,0.086909,0.139073,0.105263,...,0.0,0.0,NaN,0.0,0.5,0.646018,0.0,0.0,0.458702,0.137857
1,392291.0,3.2,0.480526,0.0,0.599283,0.531993,0.063272,0.053905,0.056291,0.105263,...,0.0,0.0,NaN,0.0,0.5,0.646018,0.0,0.0,0.458702,0.137857
2,392291.0,3.2,0.52839,0.0,0.675269,0.531993,0.078704,0.042904,0.072848,0.105263,...,0.0,0.0,NaN,0.0,0.5,0.646018,0.0,0.0,0.458702,0.137857
3,392291.0,3.2,0.481933,0.0,0.620072,0.531993,0.109568,0.053905,0.089404,0.105263,...,0.0,0.0,NaN,0.0,0.5,0.646018,0.0,0.0,0.458702,0.137857
4,392291.0,3.2,0.535429,0.0,0.750538,0.531993,0.140432,0.086909,0.139073,0.105263,...,0.0,0.0,NaN,0.0,0.5,0.646018,0.0,0.0,0.458702,0.137857

In [8]:
df_normalize.to_csv('mes_donnees_normalisées.csv', sep=';', index=False, encoding='utf-8-sig') #exportation des données normalisées en csv